### ISSUE TITLE
Omeka minimum version

### ISSUE THREAD

**Issue by ebellempire** [UCSCLibrary/AdminImages#1]
I'm getting the following error (Omeka 2.1.4):

`Fatal error: Class 'Omeka_Form_SessionCsrf' not found in /path/to/plugins/AdminImages/controllers/ImageController.php on line 27`

If I recall from browsing around the Omeka forums, this class is specific to Omeka 2.2+

**Comment by NedHenry** [comment]
You are correct Erin. We are upgrading our csrf protection to use this form
this week, so not all the kinda are worked out yet. Thanks for reporting
this bug with earlier versions of Omeka. We will address this as soon as
possible.
Best,
Ned

**Comment by NedHenry** [comment]
Hi Erin,
The latest commit to AdminImages should disable csrf protection for Omeka
versions 2.2.1 and below. However, I strongly recommend updating Omeka if
this is plausible for you to do. The security update in 2.2.1 is rather
important. There is a chance that in the future we will stop maintaining
our plugins for earlier versions.
Keep in mind that similar bugs may pop up in our other plugins for a short
time as we update csrf protection in each of them.
All the best,
Ned

**Comment by ebellempire** [comment]
Thanks @NedHenry. I've advised my clients to upgrade their installation, but this appears to have fixed the issue in the meantime. Cheers.
