### ISSUE TITLE
Add Info to README

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/AdminImages#3]
Add info to README file about how to use Admin Images for carousels or other site design elements (does not need to be exhaustive, just a brief overview)

**Comment by NedHenry** [comment]
I added a very brief overview of how to use the plugin. Do you think we need to add more detail about how you might use an image url in an html page?

**Comment by JessWaggs** [comment]
I don't think we need to add that level of detail, this looks good to me!
