### ISSUE TITLE
Admin Image shortcode in Simple Page

### ISSUE THREAD

**Issue by jim1001** [UCSCLibrary/AdminImages#7]
Just want to check if the _Admin Image_ shortcode can only be used for basic formatting of the image on a _Simple Page_ using the options specified under _File_ of the _Built-in Shortcodes_ section of the _Omeka Classic User Manual_.

Say if I wanted the image to be inline, left-justified with text flowing around the right of it separated by a margin, I couldn’t use the shortcode but would have to use the _img_ html tag & the URL of the _Admin Image_  - is that right?

Grateful for any clarification - thank you.

**Comment by NedHenry** [comment]
Yes, what you say is entirely correct to the best of my understanding.
Best!

**Comment by jim1001** [comment]
OK, that’s fine, thank you for the confirmation.

**Comment by DBinaghi** [comment]
I've taken care of that in my fork of this plugin: now you can pass a specific style class a parameter of the shortcode.
Hope my upgrades will be included in the original plugin soon.

**Comment by jim1001** [comment]
Thanks for your note and your work. Sadly I no longer work with Omeka so
won't be able to try it, but I'm sure there'll be others who will benefit
from your improvement. All the best. Jim
